# Content-based Filtering

Follow by [C4-W2-Recommender-System](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/recommendation_systems/solutions/content_based_by_hand.ipynb)

In [1]:
import numpy as np
import pandas as pd

In [3]:
users = ["Ryan", "Danielle", "Vijay", "Chris"]

movies = [
    "Star Wars", "The Dark Knights", "Shrek",
    "The Incredibles", "Bleu", "Memento"
]

features = ["Action", "Sci-fi", "Comedy", "Cartoon", "Drama"]

In [4]:
num_users = len(users)
num_movies = len(movies)

num_feats = len(features)

num_recommendations = 2

In [5]:
user_movies = np.array([
    [4,  6,  8,  0, 0, 0],
    [0,  0, 10,  0, 8, 3],
    [0,  6,  0,  0, 3, 7],
    [10, 9,  0,  5, 0, 2]
]).astype(np.float32)

movie_feats = np.array([
    [1, 1, 0, 0, 1],
    [1, 1, 0, 0, 0],
    [0, 0, 1, 1, 0],
    [1, 0, 1, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 0, 0, 0, 1]
])

In [6]:
np.matmul(user_movies, movie_feats)

array([[10., 10.,  8.,  8.,  4.],
       [ 3.,  0., 10., 10., 11.],
       [13.,  6.,  0.,  0., 10.],
       [26., 19.,  5.,  5., 12.]])

In [7]:
np.sum(np.matmul(user_movies, movie_feats), axis=1, keepdims=True)

array([[40.],
       [34.],
       [29.],
       [67.]])

In [8]:
# multi-casting
# normalizing user_feats

user_feats = np.matmul(user_movies, movie_feats)

user_feats /= np.sum(user_feats, axis=1, keepdims= True)

In [9]:
user_feats

array([[0.25      , 0.25      , 0.2       , 0.2       , 0.1       ],
       [0.08823529, 0.        , 0.29411765, 0.29411765, 0.32352941],
       [0.44827586, 0.20689655, 0.        , 0.        , 0.34482759],
       [0.3880597 , 0.28358209, 0.07462687, 0.07462687, 0.17910448]])

In [24]:
top_k_movies_ids = np.argsort(user_feats, axis=1)[:, -num_recommendations:]

top_k_movies_ids

array([[1, 0],
       [3, 4],
       [4, 0],
       [1, 0]])

In [25]:
top_k_movie_scores = np.take(user_feats, top_k_movies_ids)

top_k_movie_scores

array([[0.25, 0.25],
       [0.2 , 0.1 ],
       [0.1 , 0.25],
       [0.25, 0.25]])